---
image: node:7.2.1

stages:
  - build
  - test
  - dockerize
  - deploy

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules/

before_script:
    - export PATH=$PATH:node_modules/.bin
    - npm install

build:
  stage: build
  script:
    - ng build --prod --output-path dist/empurrandojuntos --deploy-url /
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  stage: test
  script:
    - ng test --code-coverage --single-run
  artifacts:
    expire_in: 1 week
    paths:
        - coverage/*

dockerize:
  stage: dockerize
  image: docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker create --name frontend nginx
    - docker cp dist/empurrandojuntos/. frontend:/usr/share/nginx/html/
    - docker commit frontend registry.gitlab.com/empurrandojuntos/frontend:latest
    - docker push registry.gitlab.com/empurrandojuntos/frontend:latest
    - docker rm frontend
  dependencies:
    - build

pages:
  stage: deploy
  script:
    - ls -la
    - ls -la dist/
    - rm -rf public/*
    - mkdir -p public/
#    - mv landing-page/* public/
    - mv dist/empurrandojuntos/* public/
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  dependencies:
    - build
#  only:
#    - master
