---
image: docker:git

services:
- docker:dind

stages:
  - build
  - test
  - deploy

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - node_modules/

before_script:
    - export NODE="docker run --rm -u node -v $PWD:/app -w /app node:7.2.1"
    - $NODE npm install

build:
  stage: build
  script:
    - $NODE ./node_modules/.bin/ng build --prod --output-path dist/empurrandojuntos --deploy-url /
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker create --name frontend nginx
    - docker cp dist/empurrandojuntos/. frontend:/usr/share/nginx/html/
    - docker commit frontend registry.gitlab.com/empurrandojuntos/frontend:latest
    - docker push registry.gitlab.com/empurrandojuntos/frontend:latest
    - docker rm frontend
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  tags:
    - docker

test:
  stage: test
  script:
    - $NODE ./node_modules/.bin/ng test --code-coverage --single-run
  artifacts:
    expire_in: 1 week
    paths:
        - coverage/*

pages:
  stage: deploy
  script:
    - ls -la
    - ls -la dist/
    - rm -rf public/*
    - mkdir -p public/
#    - mv landing-page/* public/
    - mv dist/empurrandojuntos/* public/
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  dependencies:
    - build
#  only:
#    - master
