image: docker:18.01.0-ce-git
services:
  - docker:dind
stages:
  - test
  - push image
  - deploy

# Stage: test
test:
  stage: test
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - docker-compose -f docker-compose.test.yml run angular
  tags:
    - docker

# Stage: push image
push develop image:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker build -f ./compose/production/angular/Dockerfile -t ej-build-angular .
    - docker run --rm -v $PWD:/app -w /app ej-build-angular homolog dist/ej /
    - docker build -f ./compose/production/nginx/Dockerfile -t $DOCKER_HUB_ORGANIZATION/ej-frontend:develop .
    - docker push $DOCKER_HUB_ORGANIZATION/ej-frontend:develop
  only:
    - /develop/
  tags:
    - docker

push production image:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker build -f ./compose/production/angular/Dockerfile -t ej-build-angular .
    - docker run --rm -v $PWD:/app -w /app ej-build-angular
    - docker build -f ./compose/production/nginx/Dockerfile -t $DOCKER_HUB_ORGANIZATION/ej-frontend:latest .
    - docker push $DOCKER_HUB_ORGANIZATION/ej-frontend:latest
  only:
    - /master/
  tags:
    - docker

push release image:
  stage: push image
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
    - docker build -f ./compose/production/angular/Dockerfile -t ej-build-angular .
    - docker run --rm -v $PWD:/app -w /app ej-build-angular
    - docker build -f ./compose/production/nginx/Dockerfile -t $DOCKER_HUB_ORGANIZATION/ej-frontend:$CI_COMMIT_TAG .
    - docker push $DOCKER_HUB_ORGANIZATION/ej-frontend:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - docker

# Stage: deploy
deploy to development:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  environment: develop
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service frontend --no-finish-upgrade
  only:
    - /develop/
  tags:
    - docker

deploy to production:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  environment: production
  script:
    - upgrade --environment $RANCHER_ENVIRONMENT --stack $RANCHER_STACK --service frontend --no-finish-upgrade
  only:
    - /master/
  tags:
    - docker
