# Local docker-compose file
version: '3.5'

networks:
  ej:
    name: ej

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    ports:
      - '80:80'
    networks:
      - ej

  angular:
    environment:
      - THEME=${THEME:-theme-default}
    build:
      context: .
      args:
        - THEME=${THEME:-theme-default}
      dockerfile: ./compose/local/angular/Dockerfile
    env_file:
      - ./compose/local/angular.env
    ports:
      - '4200:4200'
    volumes:
      - .:/app
    networks:
      - ej
