# Local docker-compose file
version: '3.5'

networks:
  empurrando-juntos:
    name: empurrando-juntos

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    ports:
      - '80:80'
    networks:
      - empurrando-juntos

  angular:
    build:
      context: .
      dockerfile: ./compose/local/angular/Dockerfile
    env_file:
      - ./compose/local/angular.env
    ports:
      - '4200:4200'
    volumes:
      - .:/app
    networks:
      - empurrando-juntos
