version: '3.5'

networks:
  empurrando-juntos:
    name: empurrando-juntos

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    ports:
      - '80:80'
    networks:
      - empurrando-juntos

  angular:
    environment:
      - THEME=${THEME:-theme-default}
    build:
      context: .
      args:
        - THEME=${THEME:-theme-default}
      dockerfile: ./compose/local/angular/Dockerfile
    volumes:
      - .:/app
    ports:
      - '4200:4200'
    command: /start.sh
    networks:
      - empurrando-juntos
